name: Gatsby Publish

on:
<<<<<<< HEAD:.github/workflows/gatsby_publish.yml
    push:
        branches: publish
=======
  push:
    branches:
      - main
>>>>>>> a9966be1314f6234274dbb3c7d044c3bf862a226:.github/workflows/Gastby_Publish.yml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: enriikke/gatsby-gh-pages-action@v2
              with:
                  access-token: ${{ secrets.ACCESS_TOKEN }}
                  deploy-branch: gh-pages
                  gatsby-args: --prefix-paths
